# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests, e.g. python setup.py test
script:
  - python setup.py test
  - coverage run --source=home setup.py test
  - pip install coveralls
after_success: coveralls
